services:
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: staffhub_app
        working_dir: /var/www
        volumes:
            - ./backend:/var/www
        depends_on: 
            - db
        networks:
            - staffhub_net
    
    web: 
        image: nginx:alpine
        container_name: staffhub_web
        ports:
            - "8080:80"
        volumes:
            - ./backend:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - frontend
        networks:
            - staffhub_net

    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        container_name: staffhub_frontend
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        command: sh -c "npm install ; npm run dev -- --host 0.0.0.0 --port 5173"
        ports:
            - "5173:5173"
        networks: 
            - staffhub_net
    
    db: 
        image: mysql:8.0
        container_name: staffhub_db
        environment: 
            MYSQL_DATABASE: staffhub
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: staffhub
            MYSQL_PASSWORD: staffhub123
        ports: 
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - staffhub_net
    
volumes:
    db_data:
networks:
    staffhub_net:
        driver: bridge