name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # FRONTEND
      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Deploy frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: frontend/dist/
          server-dir: public_html/

      # BACKEND
      - name: Deploy backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: backend/
          server-dir: laravel_app/
          exclude: |
            **/.git*
            **/.env
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/Dockerfile
            **/phpunit.xml
            **/README.md
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/testing/**
            **/storage/logs/**